### PR TITLE
Add support cookie testing in controller tests

### PR DESCRIPTION
**Pull request by kenjis**
This PR adds the functionality to test response cookies in controller testing.
See #86.

*controller*:
~~~php
		$cookie = [
			'name'   => 'The-Cookie-Name',
			'value'  => 'The Value',
			'expire' => '86500',
			'domain' => '.some-domain.com',
			'path'   => '/',
			'prefix' => 'myprefix_',
			'secure' => TRUE
		];
		$this->input->set_cookie($cookie);
~~~

You can assert the cookie value.

*test code*:
~~~php
		$output = $this->request('GET', 'set_cookie/all_params');
		$this->assertResponseCookie(
			'myprefix_The-Cookie-Name', 'The Value'
		);
~~~

You can also assert more cookie params.

*test code*:
~~~php
		$cookie = [
			'value'  => 'The Value',
			'domain' => '.some-domain.com',
			'path'   => '/',
			'secure' => TRUE,
			'httponly' => FALSE,
		];
		$this->assertResponseCookie(
			'myprefix_The-Cookie-Name', $cookie
		);
~~~

### CODE REVIEW

**Comment by esetnik** [comment]
@kenjis it's working well for me. I did notice that the PR is failing tests due to `CI_Input::post() expected to be invoked 1 times, but invoked 0 times.`

I'm getting the same error in my tests when I try to use `$this->verifyInvokedOnce()` but it's not specific to this PR it also fails with that error on v0.10.1

**Comment by kenjis** [comment]
Thank you.

Yes, I have to check the test. I will look into it.
Actually, all the tests pass on my Mac OS X.

**Comment by kenjis** [comment]
@esetnik 

> I'm getting the same error in my tests when I try to use $this->verifyInvokedOnce() but it's not specific to this PR it also fails with that error on v0.10.1

The error with this PR is using `MonkeyPatch::verifyInvokedOnce()`, not `$this->verifyInvokedOnce()`.
And `$this->verifyInvokedOnce()` is just a wrapper to method of PHPUnit mock object.
I think your error has nothing to do with the error.

**Comment by kenjis** [comment]
All tests pass on my Linux...

**Comment by kenjis** [comment]
I was able to reproduce the fail. It seems there is a bug in build process for travis-ci.

**Comment by kenjis** [comment]
No, it is a bug in *Monkey Patching*.

**Pull request merged**
