### PR TITLE
Improvements for installer

### PR DESCRIPTION
**Pull request by bellflower2015**

### CODE REVIEW

**Comment by kenjis** [comment]
Why do you need this change?

**Comment by bellflower2015** [comment]
e.g., situations as following:

```
project/
|-- app_front/   (application A)
|   `-- public/   (docroot A)
|-- app_admin/   (application B)
|   `-- public/   (docroot B)
`-- vendor/   (composer autoload)
```

**Comment by kenjis** [comment]
I see. I merged your PR.
Thanks!

**Comment by bellflower2015** [comment]
Thanks a lot :)

**Comment by kenjis** [comment]
@bellflower2015 I've updated the installer in `dev-master` for CodeIgniter 3.0.6.
If you should have any problems, feel free to report it.

**Pull request merged**
