### PR TITLE
add documentation for requests to controllers using remap

### PR DESCRIPTION
**Pull request by esetnik**

### CODE REVIEW

**Comment by kenjis** [comment]
Why do you need this?

**Comment by esetnik** [comment]
I am using `_remap()` in my controller and didn't realize that I would need to call it explicitly in the `$this->request()` since it is called automatically during normal application execution. I thought it might be helpful for other devs to see that in the documentation because it took me an hour or so of digging to figure out why _remap logic was not executed in my tests.

**Comment by kenjis** [comment]
> didn't realize that I would need to call it explicitly in the $this->request() since it is called automatically during normal application execution. 
 
You don't need to call `_remap()` explicitly if you request to URI string (like the second test).

The first test is a test for the `_remap()` method.

`$this->request()` has two behaviors:

* If you pass an array to the 2nd argument of `$this->request()`, it calls the controller method which you specify in the array directly.
* If you pass string to the 2nd argument of `$this->request()`, it resolves the route (and `_remap()`) and calls the method which is resolved.

**Comment by esetnik** [comment]
Yeah I figured that out after digging into the Remap_test example, but it's not obvious from the documentation that the behavior of uri string vs. array would not be the same.

**Comment by kenjis** [comment]
I got your situation. 
Then, would it be better to improve the documentation about the behavior of uri string vs. array?

**Comment by esetnik** [comment]
Yes I think so. At least mention that the former invokes the routing and
the latter only calls the functions directly. In most cases it seems like
the recommended approach should be to utilize the string variant since it
most closely matches how clients would interact with a controller. And it
has the added benefit of implicit tests for proper routes configuration.

**Comment by kenjis** [comment]
How about this? #96

**Comment by kenjis** [comment]
> In most cases it seems like the recommended approach should be to utilize the string variant since it most closely matches how clients would interact with a controller. And it has the added benefit of implicit tests for proper routes configuration.

Yes.

Historically, passing an array is implemented first.
So it was documented first.

**Comment by kenjis** [comment]
I've improved the test case: https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/Remap_test.php

**Comment by esetnik** [comment]
Closed in favor of https://github.com/kenjis/ci-phpunit-test/pull/96

**Pull request closed without merging**
