### PR TITLE
Added ajax request

### PR DESCRIPTION
**Pull request by RodolfoSilva**

### CODE REVIEW

**Comment by kenjis** [comment]
Merged: https://github.com/kenjis/ci-phpunit-test/commit/7886a035331d3df069b524e9157fdd0c4f4e4db9?w=1

**Comment by kenjis** [comment]
Oh, we have to remove `$_SERVER['HTTP_X_REQUESTED_WITH']` after the request.
If not, all requests after it will be considered Ajax request.

**Comment by kenjis** [comment]
No, we don't have to. PHPUnit `backupGlobals` takes care of it.

I wrote tests: https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/101059566fb45474e44ca14efa00d0760caaf7b4

**Comment by RodolfoSilva** [comment]
All right.

**Pull request closed without merging**
