### PR TITLE
We implemented an implementation that relate to another Seeder.

### PR DESCRIPTION
**Pull request by ytetsuro**
We implemented an implementation that relate to another Seeder.
If it is useful as a function, I would like to describe tests and documentation, but do you think this such a function is useful?

This function is used as follows.

tests/fixtures/artist/Artist_Seeder.php
```php
class Artist_Seeder extends Seeder {
   public function run() {
       $this->db->query('set foreign_key_checks = 0');
       $this->db->truncate('artist');
       $this->db->query('set foreign_key_checks = 1');
       $this->db->insert('artist', ['name' => 'ed sheeran']);
   }
}
```

tests/fixtures/song/Song_Seeder.php
```php
class Song_Seeder extends Seeder {
  public function __construct() {
      parent::__construct();
      $this->depends = [
          APPPATH.'tests/fixtures/artist' => 'Artist_Seeder'
       ];
  }

   public function run() {
       $this->db->query('set foreign_key_checks = 0');
       $this->db->truncate('song');
       $this->db->query('set foreign_key_checks = 1');

       $this->db->insert('song', ['artist_id' => 1, 'name' => 'The A Team']);
    }
}
```

TestCase
```php
<?php

class SampleTest extends DbTestCase {
     public static function setUpBeforeClass()
     {
         parent::setUpBeforeClass();
 
         $CI = & get_instance();
         $CI->load->library('Seeder');
         $CI->seeder->setPath(APPPATH . 'tests/fixtures/song');
         $CI->seeder->call('Song_Seeder');
      }
...
}
```

Using this function eliminates the need to call `setPath` and `call` each time.
I think that it is very easy to use when foreign key is set to the constraint of RDB.☺️

### CODE REVIEW

**Comment by kenjis** [comment]
This function seems to be good. I will merge this when it is ready.

**Comment by ytetsuro** [comment]
Created test code PR.

https://github.com/kenjis/ci-app-for-ci-phpunit-test/pull/15

**Comment by ytetsuro** [comment]
I am not confident of the document, but the work is completed.

**Comment by kenjis** [comment]
Merged: https://github.com/kenjis/ci-phpunit-test/commit/d3f1b1c381caad229c3452d9609a3587bafb6d56

**Pull request closed without merging**
